### ISSUE TITLE
warnings when used inside ASPECT

### ISSUE THREAD

**Issue by tjhei** [GeodynamicWorldBuilder/WorldBuilder#118]
I am getting hundreds of warnings of the style
```
Building CXX object CMakeFiles/aspect.dir/contrib/WorldBuilder/source/features/fault.cc.o
In file included from ../contrib/WorldBuilder/include/world_builder/features/fault.h:23:0,
                 from ../contrib/WorldBuilder/source/features/fault.cc:20:
../contrib/WorldBuilder/include/world_builder/features/interface.h:227:14: warning: ‘WorldBuilder::Features::never_actually_usedFault’ defined but not used [-Wunused-variable]
   static int never_actually_used##klass = make_sure_compilation_unit_referenced##klass();
              ^
../contrib/WorldBuilder/include/world_builder/features/fault.h:39:5: note: in expansion of macro ‘WB_REGISTER_FEATURE_HEADER’
     WB_REGISTER_FEATURE_HEADER(Fault)
     ^
```
This is using gcc 5.4.

**Comment by MFraters** [comment]
I will look into it. What I remember is that I needed this system to have a plugin system in a library (with a application like ASPECT, this is not needed), but I never got those warnings.

**Comment by MFraters** [comment]
I just rebuild aspect plus the world builder with gcc 8.2.0 in debug mode (now building release mode) and I see no warnings. Before I go and try it with an other gcc, are there any special flags you are using?

**Comment by tjhei** [comment]
Nothing special. This is in debug mode and with deal.II 8.5 (see https://jenkins.tjhei.info/blue/organizations/jenkins/aspect-test/detail/aspect-test/117/pipeline#step-24-log-290 for details) and deal.II 9.0.1 (see https://jenkins.tjhei.info/blue/organizations/jenkins/aspect-test/detail/aspect-test/120/pipeline/23 )

**Comment by tjhei** [comment]
If you need to reproduce go into a local ASPECT directory and run:
```
docker run --rm -it -v $PWD:/src tjhei/dealii:v9.0.1-full-v9.0.1-r5-gcc5
mkdir build; cd build; cmake -G Ninja /src && ninja
```

**Comment by tjhei** [comment]
is this fixed now, @MFraters ?

**Comment by MFraters** [comment]
from my point of view it is. So let's close this one.
