### ISSUE TITLE
Dummies' question

### ISSUE THREAD

**Issue by sungho91** [GeodynamicWorldBuilder/WorldBuilder#121]
Hello.

This is Sungho Lee.
I'm struggling to make my conceptual model in ASPECT.
At this moment, I've found GeodynamicWorldBuilder.

I'm not sure it will work well, however, I've checked the compilation process of ASPECT with GeodynamicWorldBuilder.

My question would be a stupid thing.

I don't know how to run GeodynamicWorldBuilder using cookbook.
By typing "ctest", I saw "88% tests passed, 2 tests failed out of 16"
It might say almost ok.

Could you give me some command lines to run GeodynamicWorldBuilder in alone or 
with ASPECT?

Plus, how to visualize the model after running GeodynamicWorldBuilder?
Using Paraview?
In my knowledge, Paraview dose not support *.grid.

Thanks in advance

Best regards

Sungho Lee

**Comment by sungho91** [comment]
I found the way to push submodule (GWB) into ASPECT. :)

**Comment by MFraters** [comment]
Sorry for the late response. To visualize the world builder input directly through the world builder you need to have compiled the code and then use the WorldBuilderVisualization executable (as described in the manual) to make paraview file (.pvd).

If you have any other questions, feel free to reopen the issue or make a new one.
