### ISSUE TITLE
Issues on install WorldBuilder on MacOS

### ISSUE THREAD

**Issue by lmx08** [GeodynamicWorldBuilder/WorldBuilder#138]
Hi,
I'm now trying to install WorldBuilder on my Macbook, following the steps described in manual 2.2.1.2 and 2.2.2. Unfortunately, 2 errors occurred:
.........
[ 90%] Built target WorldBuilder
[ 95%] Linking CXX executable bin/WorldBuilderVisualization
[ 95%] Built target WorldBuilderApp
ld: library not found for -lomp
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/WorldBuilderVisualization] Error 1
make[1]: *** [CMakeFiles/WorldBuilderVisualization.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 98%] Built target unit_test_world_builder
make: *** [all] Error 2
.......
Can you help with the problems? many thanks!

Cheers,
mgxliu

**Comment by MFraters** [comment]
Hey mgxliu,

Thank you for raising an issue. Cmake says it cannot find the openmp library. 

The openmp library is needed for building the world builder visualizer, but not for the main library and app. So depending on what you want to do openmp might not be needed. Both the world build library and the world builder app have been successfully compiled and can already be used. 

Nonetheless, the instructions do not work in your case, so to help you getting also the visualizer working I will need some information on your system:

What version of OSX and Xcode are you using (you can easily find your xcode version by looking in the `/Aplications/` directory for a app called `Xcode-10.0.app` if you xcode is 10.0)?

Also, could you post the result the first time you ran `cmake ..` (if you still have this) and of the command `which clang` and `xcodebuild -find clang`.

Thanks,

menno

**Comment by MFraters** [comment]
Looking a bit more into the problem, I remembered that at some point OSX changed their location of where clang is placed. Older versions used `usr/local/opt/llvm/` (which the manual assumes) and newer version use `/Applications/Xcode-XX.X.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/`. I am not sure between what version this changed happened exactly, but exporting the following flags should solve your problem:

`export LDFLAGS="-L/Applications/Xcode-XX.X.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib"`
`export CPPFLAGS="-I/Applications/Xcode-XX.X.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include"`
`export CC="-I/Applications/Xcode-XX.X.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang"`
`export CXX="-I/Applications/Xcode-XX.X.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++"`

Where you need to replace the XX.X with your Xcode version. Rerunning cmake and make should work, although you might have to delete the `CMakeCache.txt` file first. Does this help?

When I find out what version they switched, I will update the manual.

**Comment by MFraters** [comment]
I have two updates on this:

1. Based on some testing with travis ci, the location change seems to have happened between xcode 9 and xcode 10.

2. I have removed the openMP dependency (see pull request #140). If you update to the newest master, the problem should go away. 

I will update the installation guide in the manual.  Please let me know whether it works for you.

**Comment by lmx08** [comment]
Hi,
Thanks for the help. After updated to the newest master, it finally worked! 
One more thing I forgot to mention, during my first installation of worldbuilder, it seems it can not find llvm, what I did is "brew install llvm" after "brew install libomp", I wonder if this is one of the reasons resulted in these errors?

Cheers,
mgxliu

**Comment by MFraters** [comment]
That is great to hear! Yes, it might have been, although it did compile the library and app. 

If you have any other questions, please let me know. If this issue is resolved, could you close it?
