### ISSUE TITLE
Details on visualization of WB model

### ISSUE THREAD

**Issue by lmx08** [GeodynamicWorldBuilder/WorldBuilder#151]
Hi,
As a new user of WB, what really confuses me is that once finished my own parameter file with WB, how can I run it and visualize the result? Anyone can give a detail description of the workflow,? Thanks in advance!
By the way, my computer system is masOS Mojave, I installed WB followed 2.2.1.2 and 2.2.2.

Cheers,
mgxliu

**Comment by MFraters** [comment]
Hey mgxliu,

Thank you for your question. If you are using the world builder as a stand-alone program you can use the `WorldBuilderVisualization` executable in the bin folder to create a `.vtu` file which can be used to visualize your parameter file. `.vtu` files can be read in by programs like paraview (see [paraview.org](http://www.paraview.org)) to do the actual visualization. You can find more info on the visualizer in section 3.10 of the [manual](https://gwb.mfraters.net/manual/manual.pdf). 

There are also example grid files included for every cookbook. Example usage of the visualizer for such a cookbook (from your build directory) is: `./bin/WorldBuilderVisualization ../cookbooks/2d_cartesian_subduction_rift/2d_cartesian_subduction_rift.wb ../cookbooks/2d_cartesian_subduction_rift/2d_cartesian_subduction_rift.grid`, or if you want to use it with for example 8 threads: `./bin/WorldBuilderVisualization -j 8 ../cookbooks/2d_cartesian_subduction_rift/2d_cartesian_subduction_rift.wb ../cookbooks/2d_cartesian_subduction_rift/2d_cartesian_subduction_rift.grid`.

Does this answer your question?

**Comment by lmx08** [comment]
Hi,
Thank you for the answer, but I still have questions:

1. I found WorldBuilderVisualization in my WorldBuilder/build/bin folder, however, I'm not sure how to execute it in terminal with command line as I use OSX.

2. Secondly, as you said:
 or if you want to use it with for example 8 threads: ./bin/WorldBuilderVisualization -j 8 ../cookbooks/2d_cartesian_subduction_rift/2d_cartesian_subduction_rift.wb ../cookbooks/2d_cartesian_subduction_rift/2d_cartesian_subduction_rift.grid.
Do you mean enter the folder build, then copy and paste the above code in a terminal? I did this, however, an error occurred:
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: AssertThrow `data_stream.good()` failed in /Users/lmx/Desktop/desktop/world_builder/WorldBuilder/visualization/main.cc at line 321: Could not find the provided convig file at the specified location: ../cookbooks/2d_cartesian_subduction_rift/2d_cartesian_subduction_rift.grid.

Abort trap: 6
 3. What are the file format of *.wb and  *.grid? If not a text, how can we build it?

4. In the manual, 2.2.6 shows a way install WB as part of ASPECT, in this way how to visualize the model before run .prm file to make sure the model is exactly we want? 

5. There're different installation cases in 2.2, any recommandations on  which is the most commom used one? 

Cheers,
mgxliu

**Comment by MFraters** [comment]
Hey,

> I found WorldBuilderVisualization in my WorldBuilder/build/bin folder, however, I'm not sure how to execute it in terminal with command line as I use OSX.

When you launch the terminal navigate to the build folder. Then you can execute programs with a `./`, so in this case `./bin/WorldBuilderVisualization`. Then you can add arguments to the program by adding them behind the program. In this the required arguments are the path to a world builder file and a path to a grid file. 

> Secondly, as you said:
    or if you want to use it with for example 8 threads: ./bin/WorldBuilderVisualization -j 8 ../cookbooks/2d_cartesian_subduction_rift/2d_cartesian_subduction_rift.wb ../cookbooks/2d_cartesian_subduction_rift/2d_cartesian_subduction_rift.grid.
    Do you mean enter the folder build, then copy and paste the above code in a terminal? I did this, however, an error occurred:
    libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: AssertThrow data_stream.good() failed in /Users/lmx/Desktop/desktop/world_builder/WorldBuilder/visualization/main.cc at line 321: Could not find the provided convig file at the specified location: ../cookbooks/2d_cartesian_subduction_rift/2d_cartesian_subduction_rift.grid.
>
>Abort trap: 6

The program is complaining that it can't find the grid file. It looks like you added a dot at the end, could you try it again without it?

> What are the file format of *.wb and *.grid? If not a text, how can we build it?

They are both just text files. You can look for examples for different geodynamic settings in the cookbook folder. These folder contain both example .wb and .grid files. For all the possibilities, you can see the manual.

> In the manual, 2.2.6 shows a way install WB as part of ASPECT, in this way how to visualize the model before run .prm file to make sure the model is exactly we want?

I do not understand what you question is here. But please not that a few week ago we changed in the development version of ASPECT how ASPECT and the world builder are linked. If you have the newest version of ASPECT, you won't need to use a submodule anymore and ASPECT is automatically shipped with version 0.2.0 of the world builder. It is also possible to use a newer version of the world builder with aspect if needed.

> There're different installation cases in 2.2, any recommandations on which is the most commom used one?

If I am reading you use case correctly, you can just install the newest development version of aspect and put the path to the wb file in the .prm file and you should be good to go. Using the world builder stand alone is useful for quickly visualizing the result of the wb file.

I hope this helps!

**Comment by lmx08** [comment]
Hi,
The answer really helps! Thanks！ What caused this problem is that I added a dot at the end. 
As I understand, when I want to build my own model, first I need to write a .wb file that define the compositional fields and temperature structure; Then, using world builder stand-alone to visualize the result and make sure the model is exactly what I want. After that, link it to ASPECT to finally specify initial compositional fields and temperature structure.
I checked ASPECT manual, "World builder file" is a global parameter that specify the name of the world builder file, is this  the directory of my own .wb file? Is there any example in ASPECT using world builder file?

Cheers,
mgxliu

**Comment by MFraters** [comment]
> The answer really helps! Thanks！ What caused this problem is that I added a dot at the end.

Great to hear that it is solved!

> As I understand, when I want to build my own model, first I need to write a .wb file that define the compositional fields and temperature structure; Then, using world builder stand-alone to visualize the result and make sure the model is exactly what I want. After that, link it to ASPECT to finally specify initial compositional fields and temperature structure.

Yes, that is correct.

> I checked ASPECT manual, "World builder file" is a global parameter that specify the name of the world builder file, is this the directory of my own .wb file? Is there any example in ASPECT using world builder file?

I still have to write the section for that in the aspect manual, but you just need to set the temperature and compositional model to `world builder`. For an example with you can also look at my phd thesis (https://thesis.mfraters.net/)

**Comment by lmx08** [comment]
Hi,
Really a good thesis! Thanks for the sharing!
1. When I run examples in cookbooks, I found an interesting thing that if I put file *.grid before *.wb, that is:
>> ./bin/WorldBuilderVisualization -j 8 ../cookbooks/2d_cartesian_subduction_rift/3d_cartesian_curved_subduction.grid ../cookbooks/2d_cartesian_subduction_rift/3d_cartesian_curved_subduction.wb

there was an error:
Could not start the World builder from file '../cookbooks/3d_cartesian_curved_subduction/3d_cartesian_curved_subduction.grid', error: AssertThrow `!(parameters.ParseStream<kParseCommentsFlag | kParseNanAndInfFlag>(isw).HasParseError())` failed in /Users/lmx/Desktop/desktop/world_builder/WorldBuilder/source/parameters.cc at line 136: Parsing errors world builder file: Error(offset 0): Invalid value.

 Showing 50 chars before and after: # ouput variables
grid_type = cartesian
dim = 3
compositions = 0

# domain of the grid
x_min = 0e3
x

 Showing 5 chars before and after: # ouput va

However, exchanging the above two files resulted in the correct model.

2. The compositional fields are visualized separately, any idea of how to integrate them into one figure with different colors? Or are you working on it?

Cheers,
mgxliu

**Comment by MFraters** [comment]
Thanks :)

1. Yes, the visualizer assumes that the first file is the .wb and the second file is the .grid file.

2. There are two ways to achieve this. On is to use Paraview and use the threshold for each composition and then color them however you want. The second way is to just use one compositional field where you use different values of that field to distinguish between the different materials. See for example section 3.3.1 of the manual on how to use fractional compositional fields.

**Comment by MFraters** [comment]
I am assuming this issue is solved. Feel free to reopen it if you feel that the issue is not solved.
