### ISSUE TITLE
 How to connect GWB to ASPECT. 

### ISSUE THREAD

**Issue by undeadfast** [GeodynamicWorldBuilder/WorldBuilder#175]
Dear friend:
It's the first time I use Linux and ASPECT has already been installed in the computer. I falsed to understand all  the manual. I compiled the GWB along and I don't know how to connect GWB to ASPECT. I would like to know the detailed process of what to do.

**Comment by MFraters** [comment]
Hello,
Thanks for your question! It depends on what version of aspect you are using. A aspect version from before December 6th 2019 works with git submodules (explained below). A aspect version after that (so in the next release) it comes pre-installed with version 0.2 of the world builder, with an option to link to any version of the world builder if desired. 

I whether there is already a version of the world builder linked to aspect. When you run cmake it should tell you if whether the world builder was found or not. So if you are using aspect version 2.1.0 or lower and it didn't find the world builder, you can run `git submodule update --init` in the aspect directory. When you run cmake again it should find it. 

If you run into a specific problem, just post your cmake output here and I will take a look at it.
