### ISSUE TITLE
How to install it as part of a c program

### ISSUE THREAD

**Issue by ythaha** [GeodynamicWorldBuilder/WorldBuilder#213]
following the manual, by including the "world_builder/wrapper_c.h" to use it as part of a c program. However, this header file seems to have some problems with gcc, because the `extern " c "` indicator is not recognized.

I tried remove this, and it compiled, but when run, runtime error will show. The input worldbuiler file comes from cookbook, so the wb file should have no errors.

So, how to use it in c programs ?  thanks

**Comment by MFraters** [comment]
Hey @ythaha,
Great to hear that you want to use the world builder in your program! Thanks for letting me know that you have encountered a problem with using the C interface. I have been able to reproduce the problem and I am working on a fix and an example for you to use :)

**Comment by MFraters** [comment]
@ythaha, I have fixed the issue in pull request #214 and added an example folder which contains instructions on how to compile a c program with the world builder through gcc and with cmake. 

It now passes all the testers on travis (the main tester), but there seems to be an issue with the appveyor tester. This probably has to do with the appveyor tester itself, so I don't expect any large changes any more before it is merged. If you want you can check out that branch before it is merged and test whether it works for you, or you can wait until it is merged in the main branch.

Let me know if you have any further questions and whether the example is clear enough for you to get it working.

Cheers,

Menno

**Comment by ythaha** [comment]
it works. thank you for your help!

**Comment by MFraters** [comment]
Thanks again for reporting the issue. I am glad to hear that is is fixed now :)

When you finished including the world builder into the code feel free to make a pull request and add it to the list of codes supporting the world builder in the manual (see https://github.com/GeodynamicWorldBuilder/WorldBuilder/blob/master/doc/manual/manual.tex#L131)!
