### ISSUE TITLE
Slab tip temperature anomaly below the subducting plate for the "mass conserving" model

### ISSUE THREAD

**Issue by lhy11009** [GeodynamicWorldBuilder/WorldBuilder#353]
I discussed with @mibillen this morning the discontinuity of the slab temperature below the subducting tip.
Initially, if we look at the subducting plate (right side), the temperature below the slab tip has to increase from the temperature from a plate model to the mantle temperature.
![um_temperature000005](https://user-images.githubusercontent.com/28665365/139344438-9e826f69-7c87-471f-9511-d8b12011279f.png)
Later on in the model run, it develops as a little dripping body:
![um_temperature000013](https://user-images.githubusercontent.com/28665365/139344571-7c1d23e6-b660-4b86-8364-394bf38da192.png)
This would mass up the velocity a bit:
![um_viscosity_snap000013](https://user-images.githubusercontent.com/28665365/139344618-cfffe62a-fe53-428f-b5e8-417427bf11c3.png)
This might be an issue since I assigned a very short slab there. I would like to look into if we can fix that. Maybe, add another boundary layer below the slab tip?
Thne I changed the inputs in the .wb file to have two segments:

{ 
        "model":"subducting plate", "name":"Slab",
        "coordinates":[[4e6,-5e6],[4e6,5e6]],
        "dip point":[10e6,0],
        "segments":[
        {
            "length":314.16e3, "thickness":[300e3], "top truncation":[-100e3], "angle":[0,90],
	        "composition models":[
	        {"model":"uniform", "compositions":[0], "max distance slab top":7.5e3},
	        {"model":"uniform", "compositions":[1], "min distance slab top":7.5e3, "max distance slab top":35.2e3}
            ]
        },
        {"length":100e3, "thickness":[300e3], "top truncation":[-100e3], "angle":[90,90]}
        ],
        "temperature models":
        [
        {"model":"mass conserving", "density":3300, "thermal conductivity":3.3,"adiabatic heating":true, 
         "plate velocity":0.05,"ridge coordinates":[[0,-5e6],[0,5e6]], 
         "coupling depth":200e3, "shallow dip":60.0, "taper distance":100e3, 
         "min distance slab top":-15e3, "max distance slab top":300e3}
        ]  
    }

![Selection_999(345)](https://user-images.githubusercontent.com/28665365/139485373-419a096a-e68c-4705-9af6-318be0d8ef42.png)

**Comment by lhy11009** [comment]
### Then I changed the inputs in the .wb file to have two segments:

{ 
        "model":"subducting plate", "name":"Slab",
        "coordinates":[[4e6,-5e6],[4e6,5e6]],
        "dip point":[10e6,0],
        "segments":[
        {
            "length":314.16e3, "thickness":[300e3], "top truncation":[-100e3], "angle":[0,90],
	        "composition models":[
	        {"model":"uniform", "compositions":[0], "max distance slab top":7.5e3},
	        {"model":"uniform", "compositions":[1], "min distance slab top":7.5e3, "max distance slab top":35.2e3}
            ]
        },
        {"length":100e3, "thickness":[300e3], "top truncation":[-100e3], "angle":[90,90]}
        ],
        "temperature models":
        [
        {"model":"mass conserving", "density":3300, "thermal conductivity":3.3,"adiabatic heating":true, 
         "plate velocity":0.05,"ridge coordinates":[[0,-5e6],[0,5e6]], 
         "coupling depth":200e3, "shallow dip":60.0, "taper distance":100e3, 
         "min distance slab top":-15e3, "max distance slab top":300e3}
        ]  
    }

### Here is what it looks like
![Selection_999(345)](https://user-images.githubusercontent.com/28665365/139485373-419a096a-e68c-4705-9af6-318be0d8ef42.png)

**Comment by lhy11009** [comment]
@mibillen 
I think this largely solved the problem here. Here is a plot using the updated version (I cloned your unmerged branch)
![Selection_999(351)](https://user-images.githubusercontent.com/28665365/139521544-28b4d99f-43a4-40c0-8467-7c2c9e6f1bfd.png)
Thank for the fixing

**Comment by MFraters** [comment]
It seems like this issue is fixed now. If it is not, feel free to reopen!
