### ISSUE TITLE
Temperature step between segments using half-space and mass conserving models

### ISSUE THREAD

**Issue by rfildes** [GeodynamicWorldBuilder/WorldBuilder#373]
2D subducting slab using spherical coordinates. Looking at the temperature contours there is a discontinuity between the temperatures in in the subducting plate using the half-space model and the slab using the mass conserving model. The step is the width across one cell and gets steeper with depth (barely noticeable at shallow depths). Not an issue using these temperature models in cartesian coordinates @mibillen 
<img width="1404" alt="Screen Shot 2021-11-12 at 10 55 02 AM" src="https://user-images.githubusercontent.com/53837560/141520105-3fe5afdf-5175-4e37-817b-779c386452e3.png">
 Input file:
```
{
  "version":"0.5",
  "coordinate system":{"model":"spherical","depth method":"begin at end segment"},
  "cross section":[[0,0],[45,0]],"surface temperature":273, "force surface temperature":true,
  "potential mantle temperature":1673, "thermal expansion coefficient":3.1e-5,
  "specific heat":1250, "thermal diffusivity":1.0e-6,
  "features":
  [
    { "model":"oceanic plate", "name":"Subducting", "max depth":300e3,"min depth":-10e3,
      "coordinates" :[[25,5],[25,-5],[45,-5],[45,5]],
      "temperature models":[
        {"model":"half space model", "min depth":-10e3,  "max depth":300e3, "spreading velocity":0.03,
         "top temperature": 273, "bottom temperature":-1,
         "ridge coordinates": [[[45,-5],[45,5]]]}]
        },
    { "model":"subducting plate", "name":"Slab",
     "coordinates":[[25,-5],[25,5]],
     "dip point":[0,0],
          "segments":[{"length":200e3,"thickness":[300e3], "top truncation":[-300e3], "angle":[0,30]},
          {"length":100e3, "thickness":[300e3], "top truncation":[-300e3], "angle":[30,50]},
          {"length":700e3, "thickness":[300e3], "top truncation":[-300e3], "angle":[50,50]},
          {"length":300e3, "thickness":[300e3], "top truncation":[-300e3], "angle":[50,10]}],
         "temperature models":[{"model":"mass conserving", "density":3300, "thermal conductivity":3.3,
             "adiabatic heating":true, "plate velocity":0.03, "ridge coordinates": [[[45,-5],[45,5]]],
             "coupling depth":100e3, "shallow dip":30.0, "taper distance":100e3,
             "min distance slab top":-300e3, "max distance slab top":300e3}]
         }
  ]
}
```
grid file:
```
# Grid File for creating vtk files for temperature to view in Paraview or Visit
# output variables
#for subduction model (spherical  coordinates)
grid_type = chunk
dim = 2
compositions = 7

# domain of the grid (x and y are the surface, z is vertical with 0 at the bottom)
x_min = 0
x_max = 45
y_min = 0
y_max = 0
z_min = 3.481e6
z_max = 6.371e6

# grid properties
n_cell_x = 1350
n_cell_z = 400
```

**Comment by rfildes** [comment]
It looks like it is happening on the top truncated side of the slab as well, but only at a particular depth. I labeled the step down in the contour with a red arrow. The image is showing a uniform temperature model to show where the step down is relative to the geometry, but the contours come from my model using mass conserving and half space models. This step down, does move out with the boundary if I increase the amount of negative top truncation, but still occurs at the same temperature contour and at the boundary between the box of the mass conserving model of the slab and the half space model of the overriding plate
![Screen Shot 2021-11-15 at 4 45 49 PM](https://user-images.githubusercontent.com/53837560/142279571-70aaf552-7618-49e5-abe9-956b484e0d73.png)

**Comment by MFraters** [comment]
Thanks again for reporting it. I found out the issue with the first part. Is has to do with how the age is computed for spherical coordinates. This is affecting both the `plate model` and `half space` model for the oceanic plates. I have a fix done and will make a pull request out of it today. I am not yet sure whether it will also affect the second issue.
