### ISSUE TITLE
Error when compiling the World Builder separately

### ISSUE THREAD

**Issue by Pedrogea08** [GeodynamicWorldBuilder/WorldBuilder#375]
Hi everyone,

I have tried to compile the World Builder separately to facilitate the visualization of the geometries.

I go to aspect/contrib/world_builder and then I run cmake . and then make. However, I get the following errors:

(base) pedro_gea@cvi067044 world_builder % cmake .
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Warning at /opt/homebrew/Cellar/cmake/3.21.2/share/cmake/Modules/Platform/Darwin-Initialize.cmake:303 (message):
  Ignoring CMAKE_OSX_SYSROOT value:

   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk

  because the directory does not exist.
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.21.2/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake:21 (include)
  CMakeLists.txt:3 (project)

-- Building the Geodynamic World Builder version 0.4.0 in Debug mode
-- Found Fortran support. Enabling Fortran wrapper and tests.
-- Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR) 
-- SWIG was not found, disabling python wrapper compilation.
-- Could NOT find MPI_C (missing: MPI_C_WORKS) 
-- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS) 
-- Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND) (found version "3.1")
-- MPI not found or cmake version lower than 3.9.0.
-- Not using MPI.
-- Combining source files into unity build.
-- Found /usr/bin/diff to test the difference between files.
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/pedro_gea/aspect/contrib/world_builder
(base) pedro_gea@cvi067044 world_builder % make 
Scanning dependencies of target WorldBuilder
Consolidate compiler generated dependencies of target WorldBuilder
[  7%] Building CXX object CMakeFiles/WorldBuilder.dir/Unity/unity_0_cxx.cxx.o
In file included from /Users/pedro_gea/aspect/contrib/world_builder/CMakeFiles/WorldBuilder.dir/Unity/unity_0_cxx.cxx:3:
In file included from /Users/pedro_gea/aspect/contrib/world_builder/source/config.cc:20:
In file included from /Users/pedro_gea/aspect/contrib/world_builder/include/world_builder/config.h:24:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:506:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string_view:175:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__string:57:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:641:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:60:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string.h:60:15: fatal error: 'string.h' file not found
#include_next <string.h>
              ^~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/WorldBuilder.dir/Unity/unity_0_cxx.cxx.o] Error 1
make[1]: *** [CMakeFiles/WorldBuilder.dir/all] Error 2
make: *** [all] Error 2
(base) pedro_gea@cvi067044 world_builder % 

Any ideas as to the cause of the problem?

My operating system is MacOs BigSur and the computer has the new M1 processor. I already had problems during the installation of ASPECT. Here is the discussion I had in case it can help: 

https://community.geodynamics.org/t/error-once-i-have-compiled-aspect/1989

Thanks!

Pedro

**Comment by MFraters** [comment]
Hello Pedro,
Sorry for the late reply. I totally missed this message. I don't have a Mac with an M1 processor to test with. Looking at it it seems like your xcode installation has an issue, but it could also be something simpler. Could you try the following:

1. Remove CMakeCache.txt from the aspect/contrib/world_builder directory
2. make a build directory  and run cmake from there, use `cmake ..`

Does that solve your problem?

Again, sorry for my late reply!

**Comment by MFraters** [comment]
I am assuming the the issue is resolved. Feel free to reopen if that is not the case.
