### ISSUE TITLE
Add a code of conduct to the GWB

### ISSUE THREAD

**Issue by MFraters** [GeodynamicWorldBuilder/WorldBuilder#385]
Since the GWB has been attracting new users, and is expected to grow more, I think it a good time to add a code of conduct repository. 

The code of conduct of ASPECT is based on https://www.contributor-covenant.org, which looks good to me. I will have to take a closer look at what the differences are between version 1.4 and 2.0 of the code. 

I can't use the exact same code of conduct, since it contains specific CIG language and the GWB is not currently part of CIG. That part can be revised if that happens in the future.

**Comment by MFraters** [comment]
The GWB is now part of CIG, so the CIG specific language should be fine. @ljhwang and @gassmoeller, any opinions what the best way forward is?

**Comment by ljhwang** [comment]
I think you should adapt and/or reuse what you feel is appropriate for the project.  With regards to the mentioning of CIG. I am ok with the current ASPECT language but trying to verify if that address still exists ...

**Comment by MFraters** [comment]
ok, thanks. I need to look into it a bit more then. Let's discuss this during the hack, that would probably be easiest :)
