### ISSUE TITLE
multi-property query

### ISSUE THREAD

**Issue by MFraters** [GeodynamicWorldBuilder/WorldBuilder#409]
Currently you can only ask for one property a time (Temperature, composition 0, composition 2, grains 0 with 100 grains, grains 1 with 1000 grains, etc.)

The most expensive part of most models is actually trying to find out where in the model a certain point is, which has to be done for every call. For the same point the answer for each feature is going to be the same, so if you are asking temperature and 5 compositions for example, the same expensive computation is done 6 times, while it only needs to be done once. 

I am currently thinking of a new interface and this is what I have in mind:
```
std::vector<double> properties(const std::array<double, 3> &point, 
                               const double depth, 
                               const std::vector<std::array<int,3>>& properties);
```

`point` and `depth` are the same as the normal interfaces. Properties would be a vector where each entry is an array. The first entry of the array is an enum (int) whether the query is about temperature, composition or grains. The second entry is in case of composition or grains the composition number, and the third entry is in case of grains the number of grains.

The output is a vector of doubles, where a temperature or composition entry would be one entry, grains would be many entries. This would complicated the reading of the output a bit in case grains are used, but since the caller knows what they asked for, they can know exactly what each entry means. Both the input and output are easy to pass through a C-interface, which is also an advantage.

A different option would be to go for a vector of void pointers, which either point to a double or a grains struct, but that would require memory management on the side of the caller, so this is probably a cleaner solution.

This can probably be easily used in the world builder visualizer and app, but it will be harder to use in ASPECT. I took a quick look at it and because all properties, including each composition, are called individually, they can not easily take advantage of this. The only item would could probably easily benefit from this is the CPO plugin. It may be possible to reorganize the compositions so that they can be queried all at once, but that would probably be a significant amount of work. @bangerth @tjhei @gassmoeller, any thoughts on this?

**Comment by tjhei** [comment]
This is about interpolating initial conditions for temperature/composition, etc. right?

Because the user can pick different ways to interpolate initial data for different fields (say a function for temperature but worldbuilder for a composition), we do the interpolation for each field individually.

The initial conditions for temperature and compositions are handled completely separately and unifying them is somewhat difficult. One thing we could do is interpolate all compositional fields at once instead of one at a time. Not sure how useful that is, but this could be done with a little bit of work.

**Comment by MFraters** [comment]
> This is about interpolating initial conditions for temperature/composition, etc. right?

Yes, and potentially the boundary conditions if they are set to initial conditions.

> Because the user can pick different ways to interpolate initial data for different fields (say a function for temperature but worldbuilder for a composition), we do the interpolation for each field individually:
https://github.com/geodynamics/aspect/blob/b6ccfadb4fe89ce273d87fcbec20bc438a7ba783/source/simulator/initial_conditions.cc#L73-L124
>
> The initial conditions for temperature and compositions are handled completely separately (in different plugins) and unifying them is somewhat difficult. One thing we could do is interpolate all compositional fields at once instead of one at a time. Not sure how useful that is, but this could be done with a little bit of work.

Yes, unifying temperature and compositional plugins would probably be a step too far. Unifying the compositional fields could still be significantly beneficial for models which use the world builder to compute at least a few compositions with faults or slabs in them and where the world builder is taking a significant amount of time. You would still "pay" for the first composition, but every next composition would be almost free in comparison. Whether that is worth the effort, I don't know, but it may be good to talk about it during the hackaton.

**Comment by tjhei** [comment]
> Whether that is worth the effort, I don't know, but it may be good to talk about it during the hackaton

Sounds good!  The change is not very difficult...

**Comment by MFraters** [comment]
good to know, thanks :)
