### ISSUE TITLE
Input dip point in degrees using spherical coordinate system

### ISSUE THREAD

**Issue by alarshi** [GeodynamicWorldBuilder/WorldBuilder#446]
When using dipping faults in WB for the global mantle flow models, I realized that the `dip point` in the JSON file (internally used as `reference_point` in WB) needs to be in radians and not degrees as the longitudes/latitudes of the fault trace. 
Maybe for consistency, we would want to give the `dip point` in degrees when using the spherical coordinate system.

**Comment by MFraters** [comment]
Thanks for opening an issue about this. I agree that it makes more sense to have the dip point in degrees. I will make a fix for that.
