### ISSUE TITLE
Add Bezier curve

### ISSUE THREAD

**Issue by MFraters** [GeodynamicWorldBuilder/WorldBuilder#449]
Based on the work done for #429, I found that using Bezier curves should be a lot more reliable and faster since it has a closed form solution. I think the Bezier curves should be added for slab and fault coordintes and maybe even replace the continuous monotone spline.

**Comment by MFraters** [comment]
Here is a comparison between the Contiuous Monotone Spline (CMS) and the Bezier curve for a 3d spherical subducting slab setting.

![3d_spherical_slab_depth_temp_contour_CMS-vs-Bezier_above](https://user-images.githubusercontent.com/7631629/200497360-7e84a5e7-e660-4afe-9822-cc5bcd2ab8e3.png)
![3d_spherical_slab_depth_temp_contour_CMS-vs-Bezier_below](https://user-images.githubusercontent.com/7631629/200497363-8f9f6d7e-3c59-4e59-8bb3-5f6c0512564e.png)


 You can argue over which is better, but the Bezier curve approach is definitely smoother. I personally think the Bezier approach is both numerically (more stable, no iterations which can fail and should be faster) and visually better. The CMS follows the points with less curvature, but if you really want that you can just add more points.

Looking at these results I now more strongly think that the CMS approach should be replaced by the Bezier curve approach, unless major drawbacks are found in the mean time of course. Although both could be supported, I don't see much of an advantage and it would make the code a lot more complicated and harder to maintain (and also allow users to get hard errors that an iteration failed).

May be of interest to @alarshi, @danieldouglas92 since it will (I think only slightly) change initial conditions compared to the current main branch.

**Comment by danieldouglas92** [comment]
I also agree that the Bezier curve does look better! I'm excited to try it once it's implemented
