### ISSUE TITLE
BezierCurve::closest_point_on_curve_segment sometimes throws exceptions

### ISSUE THREAD

**Issue by gassmoeller** [GeodynamicWorldBuilder/WorldBuilder#488]
These lines sometimes throw exceptions: https://github.com/GeodynamicWorldBuilder/WorldBuilder/blob/a350135523449e4b4d633313d59bb74e8e34b008/source/world_builder/objects/bezier_curve.cc#L484

I am still working out under which conditions / for which points, but it seems the newton solver does not always find a good solution.

I will report back when I have found the exact conditions (bezier_curve / point coordinates) for which this happens.

**Comment by MFraters** [comment]
I think we discussed this, did you use the latest version of the world builder?
