### ISSUE TITLE
Dealing with the overlaps of multiple compositional fields

### ISSUE THREAD

**Issue by lmx08** [GeodynamicWorldBuilder/WorldBuilder#521]
Hi,
The example from Listing 13 in the manual (version 0.5.0-pre) decribes the way to define multiple compositional fields. However, it seems that when there is a overlap, the overlap parts should be deducted from the compositional field aheads the last composition definition.  For example: 
{
  "version": "0.6",
  "cross section":[[0,0],[3500,0]],
  "features":
  [
	
	{"model":"continental plate", "name":"CPA", "coordinates":[[0e3,0e3],[3500e3,0e3],[3500e3,300e3],[0e3,300e3]],
         "temperature models":[{"model":"linear", "max depth":300e3, "bottom temperature":1573}],
         "composition models":[{"model":"uniform", "compositions":[0], "max depth":100e3},
                               {"model":"uniform", "compositions":[1], "min depth":0e3, "max depth":200e3},
			       {"model":"uniform", "compositions":[2], "min depth":200e3, "max depth":300e3}]}
   
	

  ]
}
In this model, the overlap part between C0 and C1 will be deducted from C0.

When we want to use "strain weakening" function in ASPECT, we should first define a compositional field in which the strain weakening can be used, and this composotional field always overlaps with the crust composition. So is it possible to use GWB
to prepare the initial model for ASPECT that can use the  strain weakening function?

Thanks!

**Comment by MFraters** [comment]
Hey,

Thanks for your question. Yes, this is definitely possible. There is an option in every temperature and compositional model called `operation`. The default is `replace`, but `add` and `subtract` are also available. For composition models there is also a `replace defined only` operation. By default is will overwrite all compositional fields, but with this option, it will only overwrite the compositional fields which are defined for that compositional model. So I first define my other compositions and then add the strain composition. That looks like this:
```
"composition models":[{"model":"uniform", "compositions":[3], "fractions":[1], "operation":"replace defined only"}]
```
This is how I add strain to my aspect models (composition 3 for me). Let me know if this works for you.

**Comment by lmx08** [comment]
Hey,
Thanks for the answer, this really help. Recently I read the GWB manual, several questions that really confused me:
1.     In Listing 10, you give an example of using the feature ”fractions”. To my understanding, this is the function for creating 2 compositions, that is C1 and C4. However, when I drew this figure, things didn’t go like this, C1 and C4 overlapped. 
2.     What’s the temperature structure of the “mantle layer”?
3.     In Listing 19，what’s the coordinate 1 in “sections” refers to? And in Figure 3.4, what do 1, 50 and 99 in the title of each figure mean? 1 refers to coordinate 1?
 
Besides, there are other questions of using ASPECT. In your Dr’s thesis, 
1.     section 4.8 Appendix B: ASPECT input:
![图片 1](https://github.com/GeodynamicWorldBuilder/WorldBuilder/assets/22949764/675859f2-8d25-40dd-a896-8044ccd3f356)

Three geometries were defined, however, aspect’s manual states that we can choose only one from all the patterns. When you defined material model, there are also two patterns: Visco Plastic and Multicomponent. Is it reasonable and executable? How？

**Comment by MFraters** [comment]
Great to hear that the answer helped!

1. It sounds like you used the old pdf manual. There is a new, up-to-date and much improved manual here: gwb.readthedocs.io
2. If you don't prescribe a temperature model, it doesn't overwrite whatever is there. The background for any world builder model is an adiabatic temperature, see: https://gwb.readthedocs.io/en/latest/user_manual/basic_starter_tutorial/02_your_first_input_file.html
3. See comment one. If you find any issue with the new manual, please point me to the page directly or make a separate issue/pull request. These questions are greatly appreciated though, so if you find any issue with the manual (clarity or typoes) please let me know!
4. Aspect only uses the model defined in the "set model name = ". The box and Ellipsoidal chunk where left there from earlier experimentation and could have been removed. Same holds for the material model. Only one is used (Visco Plastic)

Let me know if you have any further questions!
