### ISSUE TITLE
Linear constant dip faults create circular features at depth

### ISSUE THREAD

**Issue by danieldouglas92** [GeodynamicWorldBuilder/WorldBuilder#522]
When trying to create a constant dipping linear fault feature, one of the points on the fault turns into a radial feature at depth. I attached screenshots of the linear fault at the surface and at depth, showing this behaviour. I also attached the grid file and worldbuilder file that I used. 

![image](https://github.com/GeodynamicWorldBuilder/WorldBuilder/assets/55814099/50c75fdd-34da-470a-b82e-1515b38c9669)

![image](https://github.com/GeodynamicWorldBuilder/WorldBuilder/assets/55814099/d17703e7-bb88-47cc-8435-f9a80d67ffee)

[grid.txt](https://github.com/GeodynamicWorldBuilder/WorldBuilder/files/13541573/grid.txt)
[fault_rings.txt](https://github.com/GeodynamicWorldBuilder/WorldBuilder/files/13541574/fault_rings.txt)

**Comment by MFraters** [comment]
Thanks for reporting the issue. I have an idea what could be causing the issue, but I will need some more time to investigate it. It seems for the points on one side to include the end point in the distance calculation, which is causing this circular shape. I heard form you that you had found a case where it doesn't do this, can you also post that input file? Thanks!

**Comment by MFraters** [comment]
@danieldouglas92, well finding the issue was easier than expected (see #523). I will now need to do quite a bit of testing. With AGU and the holidays coming up, I can't promise that it will be done before the new year, but can you give it a go as well to see if that pull request breaks any of your current models?

**Comment by MFraters** [comment]
closed by #523
