### ISSUE TITLE
Rename `anullus` to `annulus`?

### ISSUE THREAD

**Issue by jdannberg** [GeodynamicWorldBuilder/WorldBuilder#539]
I noticed that the gwb-grid app has an input option for the grid type called `anullus` (while the correct spelling would be `annulus`). It would be good to change it, but then I guess that would break some old files? @MFraters how would you want to handle that?

**Comment by MFraters** [comment]
Good find! Given that this is obviously wrong and we are not in the first major version yet, I think it is oke to break this. I seriously doubt anyone is currently using it and the update would be trivial. So adding an entry to the changelog would be sufficient in this case I think.
