### ISSUE TITLE
Random number seed as input for generating different random textures

### ISSUE THREAD

**Issue by Wang-yijun** [GeodynamicWorldBuilder/WorldBuilder#575]
Currently, the random uniform distribution grains model can only generate the same random texture using the random number generator since the seed is hard-coded to be 1. It will be more helpful if the random number seed can be an argument in the *.wb file or *.dat file, while still having a reproducible random texture. I'm not sure what's the best way to do this @MFraters

**Comment by MFraters** [comment]
related to #584

**Comment by MFraters** [comment]
@Wang-yijun I think this is resolved now?

**Comment by Wang-yijun** [comment]
Yes, thanks!
