### ISSUE TITLE
properties() documentation is wrong

### ISSUE THREAD

**Issue by tjhei** [GeodynamicWorldBuilder/WorldBuilder#580]
the id 2 doesn't seem right:
https://github.com/GeodynamicWorldBuilder/WorldBuilder/blob/8fe8ca7b62e2d2c0d72a79c514fe4c245bd7644f/include/world_builder/world.h#L126

@MFraters

**Comment by MFraters** [comment]
Good point. I am fixing it in #594

**Comment by MFraters** [comment]
Fixed!
