### ISSUE TITLE
Define an intergar variable in file source/world_builder/features/subducting_plate_models/temperature/mass_conserving.cc

### ISSUE THREAD

**Issue by lhy11009** [GeodynamicWorldBuilder/WorldBuilder#658]
I defined an integer variable in the file with

          prm.declare_entry("number of points in spline", Types::Int(2),
                            "The number of points in the spline");

When I compile, I receive an error saying:

        /home/lochy/Softwares/WorldBuilder/source/world_builder/features/subducting_plate_models/temperature/mass_conserving.cc:177:71: error: invalid use of incomplete type ‘class WorldBuilder::Types::Int’
    177 |           prm.declare_entry("number of points in spline", Types::Int(2),

    In file included from /home/lochy/Softwares/WorldBuilder/include/world_builder/coordinate_systems/interface.h:26,
                 from /home/lochy/Softwares/WorldBuilder/include/world_builder/coordinate_systems/cartesian.h:23,
                 from /home/lochy/Softwares/WorldBuilder/source/world_builder/coordinate_systems/cartesian.cc:20,
                 from 
        /home/lochy/Softwares/WorldBuilder/build_mass_conserving_spline_new/CMakeFiles/WorldBuilder.dir/Unity/unity_0_cxx.cxx:3:
       /home/lochy/Softwares/WorldBuilder/include/world_builder/parameters.h:44:11: note: forward declaration of ‘class 
      WorldBuilder::Types::Int’
           44 |     class Int;

I tried to include the header file but that  doesn't address the issue:
   
         #include "world_builder/parameters.h"

When I looked at the definition of integer variables elsewhere, I was surprised to see there only 1 case in source/world_builder/world.cc

      prm.declare_entry("random number seed", Types::Int(-1),
                        "Use random number seed input to generate random numbers.");

But there, the definition is successful.

**Comment by MFraters** [comment]
The relevant header file is in `world_builder/types/int.h`, not `world_builder/parameters.h`. Could you try that?

**Comment by lhy11009** [comment]
Yes, that solves the issue. Thanks.
