### ISSUE TITLE
confusion about the version number

### ISSUE THREAD

**Issue by lhy11009** [GeodynamicWorldBuilder/WorldBuilder#689]
I compiled my aspect on the world build 0.6.0-pre.

lochy  lochy-Inspiron-16-Plus-7620  …/aspect/build_mow_global  mow_global ◔  cmake -DWORLD_BUILDER_SOURCE_DIR=/home/lochy/Softwares/WorldBuilder ..
-- ====================================================
-- ============ Configuring ASPECT ====================
-- ====================================================
-- Setting up ASPECT for DebugRelease mode.
-- Found deal.II version 9.5.1 at '/home/lochy/Softwares/dealii/Deal.ii-9.5.1-native-32-candi-gcc-11.4.0-openmpi-4.1.5/deal.II-v9.5.1/lib/cmake/deal.II'
-- ASPECT_WITH_WORLD_BUILDER = 'ON'
-- Using World Builder version 0.6.0-pre found at /home/lochy/Softwares/WorldBuilder.
CMake Deprecation Warning at /home/lochy/Softwares/WorldBuilder/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

But I am getting the following error with version number 0.6

4: ----------------------------------------------------
4: Exception on rank 0 on processing: 
4: AssertThrow `(Version::MAJOR == "0" && prm.get<std::string>("version") == Version::MAJOR + "." + Version::MINOR) || (Version::MAJOR != "0" && prm.get<std::string>("version") == Version::MAJOR)` failed in /home/lochy/Softwares/WorldBuilder/source/world_builder/world.cc at line 159: The major and minor version combination (for major version 0) or the major version (for major versions after 0) for which is input file was written is not the same as the version of the World Builder you are running. This means That there may have been incompatible changes made between the versions. 
4: 
4: Verify those changes and whether they affect your model. If this is not the case, adjust the version number in the input file. 
4: 
4: The provided version number is "0.6", while the used world builder has  (major.minor) version "0.5". If you created this file from scratch, fill set the version number to "0.5" to continue. If you got the world builder file from somewhere, make sure that the output is what you expect it to be, because backwards incompatible changes may have been made to the code.
4: 

My assumption is the version number is not updated while I compile ASPECT, as the default Worldbuilder in ASPECT has version number 0.5.0 ?
@MFraters Can you help me to debug this?

**Comment by tjhei** [comment]
Are you switching to an external GWB? Try deleting your aspect build directory. I think Rene fixed this in https://github.com/geodynamics/aspect/pull/5578

**Comment by lhy11009** [comment]
Yes, that surely addresses this question. Thanks
