### ISSUE TITLE
Instructions on how to update to WorldBuilder-1.1 for ASPECT 2.4.0

### ISSUE THREAD

**Issue by keithmagali** [GeodynamicWorldBuilder/WorldBuilder#759]
Hello everyone!

I'm currently using ASPECT v2.4.0, and I noticed that by default, it installs World Builder v0.4.0. However, I would like to update World Builder to version 1.1 for my project.

Could you please provide detailed instructions on how I can change the World Builder version from 0.4.0 to 1.1, and link it with ASPECT 2.4.0? 

Thank you very much!

Best regards,
Keith

**Comment by tjhei** [comment]
1. Download  GWB
2. Configure ASPECT with ``cmake -D WORLD_BUILDER_SOURCE_DIR=XYZ  . `` where XYZ is the directory where you downloaded GWB.

Note that ASPECT 2.4 might not be compatible with the latest GWB and you might need to switch to the ASPECT development version as well.
