### ISSUE TITLE
Chunk build progress in fraction, not percentage.

### ISSUE THREAD

**Issue by bobmyhill** [GeodynamicWorldBuilder/WorldBuilder#82]
e.g. ../../build/bin/WorldBuilderVisualization 3d_spherical_subduction.wb 3d_spherical_subduction.grid

**Comment by MFraters** [comment]
Thank you for making this issue. I will take a look at it soon :)

**Comment by MFraters** [comment]
Fixed by #84. Thanks again @bobmyhill for reporting this!
