### ISSUE TITLE
Continental plate with a passive margin

### ISSUE THREAD

**Issue by kristofporkolab** [GeodynamicWorldBuilder/WorldBuilder#94]
Hi, 
I would like to define a continental plate with multiple segments, where one of the segments is decreasing in thickness towards an ocean (basically a typical passive margin). I have tried the "segments" parameter to define the change in the thickness, but I guess that only works for the "subducting plate" features, not for "continental plate" features. 
Do you have any tips how to approach something like this?
Cheers, 
Kristof

**Comment by MFraters** [comment]
Hey Kristof,
I have been experimenting a bit with continuous variable thickness of oceanic and continental plates, but I haven't found a good way to parameterize that in an unique and clear way. If you have suggestions they are welcome :)

What you can do to solve your problem in your case is to define multiple continental plates, which each have a smaller maximum depth towards the oceanic plate. Does that work for you?

**Comment by kristofporkolab** [comment]
Hi Menno, 
I was thinking about something similar; a linear function would be good enough. I will think more about it in the coming days. I have also tried your first suggestion (multiple continents with decreasing depth), which is also not bad. It takes a few minutes to copy-paste the continents and modify the coordinates, but it works. You can find an example of that attached as txt. It would only take another 3 minutes to make it smoother by adding further 5-10 elements. 
Of course, a function to describe this would be much simpler and elegant. 
[continent_ocean_pm.txt](https://github.com/GeodynamicWorldBuilder/WorldBuilder/files/2787217/continent_ocean_pm.txt)

**Comment by MFraters** [comment]
Oke, I will put it on the todo list. I don't know when I will get around to doing it. If you have any more suggestions in the mean time, please post them.

**Comment by MFraters** [comment]
This can now be done with the variable min and max thickness of area features. See the new tutorial (gwb.readthedocs.io, basic start tutorial) for more info. Let me know if this doesn't resolve your issue.
